version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: main
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logs:
      container_name: logs
      build:
        context: ./logging
        dockerfile: Dockerfile
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

